import { addMonths, addWeeks, addYears, differenceInCalendarDays, format, isAfter, isToday } from 'date-fns'
import type { NewTransaction, Recurrence, Transaction } from '../types'

const MAX_CATCHUP = 24

function advance(date: Date, recurrence: Recurrence): Date {
  switch (recurrence) {
    case 'weekly':
      return addWeeks(date, 1)
    case 'monthly':
      return addMonths(date, 1)
    case 'yearly':
      return addYears(date, 1)
  }
}

function latestPerGroup(transactions: Transaction[]): Map<string, Transaction> {
  const latestByGroup = new Map<string, Transaction>()
  for (const t of transactions) {
    if (!t.recurrence || !t.recurringGroupId) continue
    const current = latestByGroup.get(t.recurringGroupId)
    if (!current || new Date(`${t.date}T00:00:00`) > new Date(`${current.date}T00:00:00`)) {
      latestByGroup.set(t.recurringGroupId, t)
    }
  }
  return latestByGroup
}

/**
 * For each recurring series (grouped by recurringGroupId), finds the latest
 * dated instance and returns any further occurrences due up to today. Capped
 * so a long-dormant series can't flood the ledger in one catch-up pass.
 * Generated instances never carry over a bill split.
 */
export function dueRecurringTransactions(transactions: Transaction[]): NewTransaction[] {
  const latestByGroup = latestPerGroup(transactions)
  const today = new Date()
  const due: NewTransaction[] = []

  for (const latest of latestByGroup.values()) {
    const endDate = latest.recurrenceEnd ? new Date(`${latest.recurrenceEnd}T00:00:00`) : null
    let cursor = new Date(`${latest.date}T00:00:00`)
    let steps = 0
    while (steps < MAX_CATCHUP) {
      const next = advance(cursor, latest.recurrence!)
      if (isAfter(next, today) && !isToday(next)) break
      if (endDate && isAfter(next, endDate)) break
      due.push({
        type: latest.type,
        amount: latest.amount,
        currency: latest.currency,
        accountId: latest.accountId,
        toAccountId: latest.toAccountId ?? null,
        category: latest.category ?? null,
        payee: latest.payee ?? null,
        tags: latest.tags ?? null,
        note: latest.note,
        date: format(next, 'yyyy-MM-dd'),
        recurrence: latest.recurrence,
        recurringGroupId: latest.recurringGroupId,
        recurrenceEnd: latest.recurrenceEnd ?? null,
        excluded: latest.excluded ?? false,
        splitWith: null,
      })
      cursor = next
      steps++
    }
  }

  return due
}

export interface UpcomingOccurrence {
  latest: Transaction
  dueDate: Date
  daysUntil: number
  overdue: boolean
}

/**
 * The single next occurrence for each recurring series, regardless of
 * whether it has already been auto-generated by the catch-up pass — used to
 * surface "what's coming up" without waiting for it to actually fall due.
 */
export function upcomingOccurrences(transactions: Transaction[], withinDays = 14): UpcomingOccurrence[] {
  const latestByGroup = latestPerGroup(transactions)
  const today = new Date()

  const upcoming: UpcomingOccurrence[] = []
  for (const latest of latestByGroup.values()) {
    const dueDate = advance(new Date(`${latest.date}T00:00:00`), latest.recurrence!)
    if (latest.recurrenceEnd && isAfter(dueDate, new Date(`${latest.recurrenceEnd}T00:00:00`))) continue
    const daysUntil = differenceInCalendarDays(dueDate, today)
    if (daysUntil > withinDays) continue
    upcoming.push({ latest, dueDate, daysUntil, overdue: daysUntil < 0 })
  }

  return upcoming.sort((a, b) => a.dueDate.getTime() - b.dueDate.getTime())
}
